version: "3.8"

services:

  database:
    image: mariadb
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - "${PWD}/database:/var/lib/mysql"
      - "${PWD}/database-setup/initfile.sql:/docker-entrypoint-initdb.d/initfile.sql"
    environment:
      # passwords don't need to be super secure because we'll deploy this on
      # a hidden backend network that isn't accessible by anything outside of
      # the docker-compose environment
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      # simple default user
      - MARIADB_PASSWORD=aimlac
      - MARIADB_USER=aimlac
    hostname: "aimlac-database"

  crawlers:
    image: nodered/node-red
    networks:
      - backend
    ports:
      - 1880:1880
    depends_on:
      - database
      - models
    user: "${UID}"
    environment:
      - "AIMLAC_RSE_ADDR=${AIMLAC_RSE_ADDR}"
      - "MET_SECRET_KEY=${MET_SECRET_KEY}"
      - "MET_API_KEY=${MET_API_KEY}"
      - "OPEN_WEATHER_API=${OPEN_WEATHER_API}"
      - "LOCATION_LAT=${LOCATION_LAT}"
      - "LOCATION_LON=${LOCATION_LON}"
      - "ELEXON_API_KEY=${ELEXON_API_KEY}"
    volumes:
      - "${PWD}/crawlers/flows:/data"

  dashboard:
    image: grafana/grafana-oss
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - database
    user: "${UID}"
    volumes:
      - "${PWD}/grafana:/var/lib/grafana"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=my_adm1n_password"

  models:
    image: dustpancake/aimlac-cc-models
    networks:
      - backend
    environment:
      - "AIMLAC_RSE_ADDR=${AIMLAC_RSE_ADDR}"
      - "AIMLAC_RSE_KEY=${AIMLAC_RSE_KEY}"
      - "LOCATION_LAT=${LOCATION_LAT}"
      - "LOCATION_LON=${LOCATION_LON}"
    hostname: "aimlac-models"

  web-view:
    image: dustpancake/aimlac-cc-web-view
    networks:
      - backend
    depends_on:
      - database
    volumes:
      - "${PWD}/web-view/server/dashboard:/app/dashboard"
    environment:
      # default database user
      - "SQL_USER=aimlac"
      - "SQL_PASS=aimlac"
      - "SQL_HOST=aimlac-database"
      - "SQL_DATABASE=llanwrytd"
      - "JWT_SECRET=${JWT_SECRET}"
      - "AIMLAC_RSE_ADDR=${AIMLAC_RSE_ADDR}"
      - "AIMLAC_RSE_KEY=${AIMLAC_RSE_KEY}"
    hostname: "aimlac-web-view"
  
  nginx:
    image: nginx:1.21.6-alpine
    networks:
      - backend
    depends_on:
      - web-view
    ports:
      - 80:80
    volumes:
      - "${PWD}/nginx:/etc/nginx/conf.d"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.5.0/24
