{
 "title": "Forecast",
 "time": { "from": "now-6h", "to": "now+48h" },
 "panels": [
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  precipitationRate\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  probOfPrecipitation\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  totalPrecipAmount\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  totalSnowAmount\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  screenTemperature\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  feelsLikeTemperature\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  maxScreenAirTemp\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  minScreenAirTemp\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "MSLP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  mslp\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  windSpeed10m\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  windGustSpeed10m\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max10mWindGust\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  visibility\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  screenRelativeHumidity\nFROM metoffice_spot\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}