{
 "title": "Open Weather",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  humidity\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pressure\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature_min\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature_max\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Clouds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  clouds\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  visibility\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wind_gust\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  wind_speed\nFROM openweather_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}