name: Update Submodules

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update submodules
        run: |
          ./update-all.sh
          cd crawlers && git pull origin main && cd ..
          cd web-view && git pull origin main && cd ..
          cd models && git pull origin main && cd ..
          
          # check if we need to push
          if [[ $(git diff) ]]; then
            echo "CONTINUE=true" >> $GITHUB_ENV
          fi

      - name: Add and commit to PR
        if: env.CONTINUE == true
        uses: EndBug/add-and-commit@v9
        with:
          add: ['crawlers', 'web-view', 'models']
          message: 'updated submodule commit hash'
          push: 'origin ${{ github.event.pull_request.head.ref }}'
          default_author: github_actions